/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import source.conexion;

public class Pelicula extends javax.swing.JFrame {
    
    int x,y, codigoo = -1, codigon = -3, codigo_peli_ejemplar = -1, codigo_formato_ejemplar = -1;
    static int id_vend;
    String nombre_peli;
    java.sql.Date fecha_nacc;
    
    conexion connect = new conexion();
    DefaultTableModel dtm = new DefaultTableModel();
    DefaultTableModel dtm2 = new DefaultTableModel();
    DefaultTableModel dtm3 = new DefaultTableModel();
    
    public Pelicula(int id) {
        connect.conectarse();
        
        initComponents();
        
        this.setLocationRelativeTo(null);
        id_vend = id;
        //table
        String [] titulo = new String[]{"Codigo", "Nombre de Pelicula"};
        dtm.setColumnIdentifiers(titulo);
        jTable1.setModel(dtm);
        
        String [] titulo3 = new String[]{"Codigo", "Nombre de Pelicula"};
        dtm3.setColumnIdentifiers(titulo);
        jTable3.setModel(dtm3);
        
        //directores combo box
        ArrayList<source.Director> directores = new ArrayList<>();
        directores = connect.llenarDirectores();
        cbDirector.removeAllItems();
        for(source.Director director : directores){
            cbDirector.addItem( director.getId() + " " + director.getNombre());
        }
        //categorias combo box
        ArrayList<source.Categoria> categorias = new ArrayList<>();
        categorias = connect.llenarCategorias();
        cbCategoria.removeAllItems();
        for(source.Categoria categoria : categorias){
            cbCategoria.addItem(categoria.getDescripcion());
        }
        
        //formatos
        String [] titulo2 = new String[]{"Nombre","Precio"};
        dtm2.setColumnIdentifiers(titulo2);
        jTable2.setModel(dtm2);
        jTable4.setModel(dtm2);
        
        ArrayList<source.Formato> iformatos = new ArrayList<>();
        iformatos = connect.formatos();
        dtm2.setRowCount(0);
        for (source.Formato iForma : iformatos) {
            dtm2.addRow(new Object[]{
                iForma.getNombre_formato(),
                iForma.getPrecio(),
            });
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        Registrar = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txtDia = new javax.swing.JTextField();
        txtMes = new javax.swing.JTextField();
        txtAnno = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        cbDirector = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtTituloB = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        cbCategoria = new javax.swing.JComboBox<>();
        Director_Categoria = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        txtDescripcionC = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        txtNombreD = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        Formato = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        txt_f_precion = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        txt_f_precio = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        txt_f_nombre = new javax.swing.JTextField();
        Ejemplares = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        txtTituloB1 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        txt_cantidad = new javax.swing.JTextField();
        mover = new javax.swing.JButton();
        cerrar = new javax.swing.JButton();
        minimizar1 = new javax.swing.JButton();
        minimizar = new javax.swing.JButton();
        ColorBarra = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("RentaMovies");
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setBackground(new java.awt.Color(230, 230, 230));
        jTabbedPane1.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N

        Registrar.setBackground(new java.awt.Color(220, 220, 220));
        Registrar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(190, 200, 200));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setText("Fecha Lanzamiento");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));
        jPanel1.add(txtDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 30, -1));
        jPanel1.add(txtMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 30, -1));
        jPanel1.add(txtAnno, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, 40, -1));

        jLabel10.setText("Año");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, 30, 20));

        jLabel11.setText("Mes");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 30, -1));

        jLabel12.setText("Dia");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 20, -1));

        jLabel7.setText("Titulo");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 40, 20));

        jLabel8.setBackground(new java.awt.Color(200, 220, 220));
        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(70, 70, 70));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("P E L I C U L A");
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel8.setOpaque(true);
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 40));
        jPanel1.add(txtTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 360, -1));

        jLabel6.setText("Director");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 50, 20));

        jButton2.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        jButton2.setText("Registrar");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 90, -1, 50));

        jPanel1.add(cbDirector, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 140, -1));

        Registrar.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 580, 170));

        jPanel5.setBackground(new java.awt.Color(190, 200, 200));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel5.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 400, 90));

        jLabel17.setText("Titulo");
        jPanel5.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 40, 20));

        jLabel18.setBackground(new java.awt.Color(200, 220, 220));
        jLabel18.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(70, 70, 70));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Agergar categorias a una pelicula");
        jLabel18.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel18.setOpaque(true);
        jPanel5.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 40));

        txtTituloB.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTituloBKeyReleased(evt);
            }
        });
        jPanel5.add(txtTituloB, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 360, -1));

        jLabel19.setText("Categoria");
        jPanel5.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 60, 60, 20));

        btnAgregar.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.setToolTipText("");
        btnAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarMouseClicked(evt);
            }
        });
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        jPanel5.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 140, 110, 30));

        cbCategoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbCategoriaMouseClicked(evt);
            }
        });
        jPanel5.add(cbCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 90, 140, -1));

        Registrar.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, 190));

        jTabbedPane1.addTab("Peliculas", Registrar);

        Director_Categoria.setBackground(new java.awt.Color(220, 220, 220));
        Director_Categoria.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(220, 230, 230));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtDescripcionC.setText("ej. Ciencia Ficcion");
        txtDescripcionC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescripcionCActionPerformed(evt);
            }
        });
        jPanel4.add(txtDescripcionC, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 120, 30));

        jLabel2.setText("Descripcion");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 70, -1));

        jLabel4.setBackground(new java.awt.Color(200, 220, 220));
        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(70, 70, 70));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Categoria");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel4.setOpaque(true);
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 40));

        jButton3.setBackground(new java.awt.Color(100, 150, 150));
        jButton3.setFont(new java.awt.Font("Candara", 1, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(250, 250, 250));
        jButton3.setText("Registrar");
        jButton3.setBorderPainted(false);
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jPanel4.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 140, 40));

        Director_Categoria.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, 270, 310));

        jPanel3.setBackground(new java.awt.Color(220, 230, 230));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNombreD.setText("ej. Barlon");
        txtNombreD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreDActionPerformed(evt);
            }
        });
        jPanel3.add(txtNombreD, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 120, 30));

        jLabel1.setText("Nombre");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 50, -1));

        jLabel3.setBackground(new java.awt.Color(200, 220, 220));
        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(70, 70, 70));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Director");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel3.setOpaque(true);
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 40));

        jButton1.setBackground(new java.awt.Color(100, 150, 150));
        jButton1.setFont(new java.awt.Font("Candara", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(250, 250, 250));
        jButton1.setText("Registrar");
        jButton1.setBorderPainted(false);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 140, 40));

        Director_Categoria.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 270, 310));

        jTabbedPane1.addTab("Director / Categoria", Director_Categoria);

        Formato.setBackground(new java.awt.Color(220, 220, 220));
        Formato.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(220, 230, 230));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setBackground(new java.awt.Color(200, 220, 220));
        jLabel13.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(70, 70, 70));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("A C T U I L Z A R");
        jLabel13.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel13.setOpaque(true);
        jPanel6.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 40));

        jButton4.setBackground(new java.awt.Color(100, 150, 150));
        jButton4.setFont(new java.awt.Font("Candara", 1, 24)); // NOI18N
        jButton4.setForeground(new java.awt.Color(250, 250, 250));
        jButton4.setText("ACTUALIZAR");
        jButton4.setBorderPainted(false);
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        jPanel6.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 180, 40));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jPanel6.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 250, 90));

        jLabel5.setText("Precio Nuevo:");
        jPanel6.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        txt_f_precion.setText("ej. 2000");
        txt_f_precion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_f_precionActionPerformed(evt);
            }
        });
        jPanel6.add(txt_f_precion, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 120, 30));

        Formato.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, 270, 310));

        jPanel7.setBackground(new java.awt.Color(220, 230, 230));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_f_precio.setText("ej. 2000");
        txt_f_precio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_f_precioActionPerformed(evt);
            }
        });
        jPanel7.add(txt_f_precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 120, 30));

        jLabel14.setText("Precio");
        jPanel7.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 50, -1));

        jLabel15.setBackground(new java.awt.Color(200, 220, 220));
        jLabel15.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(70, 70, 70));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("A G R E G A R");
        jLabel15.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel15.setOpaque(true);
        jPanel7.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 40));

        jButton5.setBackground(new java.awt.Color(100, 150, 150));
        jButton5.setFont(new java.awt.Font("Candara", 1, 24)); // NOI18N
        jButton5.setForeground(new java.awt.Color(250, 250, 250));
        jButton5.setText("AGREGAR");
        jButton5.setBorderPainted(false);
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });
        jPanel7.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 140, 40));

        jLabel16.setText("Nombre");
        jPanel7.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 50, -1));

        txt_f_nombre.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        txt_f_nombre.setText("ej. CD");
        txt_f_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_f_nombreActionPerformed(evt);
            }
        });
        jPanel7.add(txt_f_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 120, 30));

        Formato.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 270, 310));

        jTabbedPane1.addTab("Formato", Formato);

        Ejemplares.setBackground(new java.awt.Color(220, 220, 220));
        Ejemplares.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(220, 230, 230));
        jPanel8.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanel8MouseMoved(evt);
            }
        });
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setBackground(new java.awt.Color(200, 220, 220));
        jLabel21.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(70, 70, 70));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("A G R E G A R");
        jLabel21.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel21.setOpaque(true);
        jPanel8.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 40));

        jButton6.setBackground(new java.awt.Color(100, 150, 150));
        jButton6.setFont(new java.awt.Font("Candara", 1, 24)); // NOI18N
        jButton6.setForeground(new java.awt.Color(250, 250, 250));
        jButton6.setText("AGREGAR");
        jButton6.setBorderPainted(false);
        jButton6.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButton6MouseMoved(evt);
            }
        });
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });
        jPanel8.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 300, 140, 40));

        txtTituloB1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTituloB1KeyReleased(evt);
            }
        });
        jPanel8.add(txtTituloB1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 290, -1));

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        jTable3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable3MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable3);

        jPanel8.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 340, 110));

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        jTable4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable4MouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jTable4);

        jPanel8.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 250, 100));

        jLabel20.setText("Pelicula");
        jPanel8.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel22.setText("Formato");
        jPanel8.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        jPanel2.setBackground(new java.awt.Color(190, 220, 215));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setText("Cantidad");
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        txt_cantidad.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        txt_cantidad.setText("ej. 10");
        txt_cantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cantidadActionPerformed(evt);
            }
        });
        jPanel2.add(txt_cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 90, -1));

        jPanel8.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 170, 110, 90));

        Ejemplares.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 550, 350));

        jTabbedPane1.addTab("Ejemplar", Ejemplares);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 600, 420));
        jTabbedPane1.getAccessibleContext().setAccessibleName("Registrar");

        mover.setBackground(new java.awt.Color(46, 51, 58));
        mover.setBorderPainted(false);
        mover.setContentAreaFilled(false);
        mover.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        mover.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                moverMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                moverMouseMoved(evt);
            }
        });
        mover.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                moverMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                moverMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                moverMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                moverMousePressed(evt);
            }
        });
        getContentPane().add(mover, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 40));

        cerrar.setBackground(new java.awt.Color(46, 51, 58));
        cerrar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cerrar.setForeground(new java.awt.Color(255, 255, 255));
        cerrar.setText("X");
        cerrar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        cerrar.setBorderPainted(false);
        cerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cerrar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                cerrarMouseMoved(evt);
            }
        });
        cerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cerrarMouseClicked(evt);
            }
        });
        getContentPane().add(cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 0, 60, 40));

        minimizar1.setBackground(new java.awt.Color(46, 51, 58));
        minimizar1.setFont(new java.awt.Font("Broadway", 1, 36)); // NOI18N
        minimizar1.setForeground(new java.awt.Color(255, 255, 255));
        minimizar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/return.png"))); // NOI18N
        minimizar1.setBorder(null);
        minimizar1.setBorderPainted(false);
        minimizar1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                minimizar1MouseMoved(evt);
            }
        });
        minimizar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizar1MouseClicked(evt);
            }
        });
        getContentPane().add(minimizar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, 60, 40));

        minimizar.setBackground(new java.awt.Color(46, 51, 58));
        minimizar.setFont(new java.awt.Font("Broadway", 1, 36)); // NOI18N
        minimizar.setForeground(new java.awt.Color(255, 255, 255));
        minimizar.setText("-");
        minimizar.setBorder(null);
        minimizar.setBorderPainted(false);
        minimizar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                minimizarMouseMoved(evt);
            }
        });
        minimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizarMouseClicked(evt);
            }
        });
        getContentPane().add(minimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 0, 60, 40));

        ColorBarra.setBackground(new java.awt.Color(46, 51, 58));
        ColorBarra.setFont(new java.awt.Font("Candara", 1, 24)); // NOI18N
        ColorBarra.setForeground(new java.awt.Color(255, 255, 255));
        ColorBarra.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ColorBarra.setText(" Gestion de Peliculas");
        ColorBarra.setToolTipText("");
        ColorBarra.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        ColorBarra.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        ColorBarra.setOpaque(true);
        ColorBarra.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                ColorBarraMouseMoved(evt);
            }
        });
        getContentPane().add(ColorBarra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 40));

        fondo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fondo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        fondo.setOpaque(true);
        fondo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                fondoMouseMoved(evt);
            }
        });
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fondoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fondoMouseMoved
        cerrar.setBackground(new Color(46, 51, 58));
        minimizar.setBackground(new Color(46, 51, 58));
        Icon foto = new ImageIcon(getClass().getResource("/img/return.png"));
        minimizar1.setIcon(foto);
    }//GEN-LAST:event_fondoMouseMoved

    private void ColorBarraMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ColorBarraMouseMoved
        minimizar.setBackground(new Color(46, 51, 58));
    }//GEN-LAST:event_ColorBarraMouseMoved

    private void moverMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moverMouseDragged
        this.setLocation(this.getLocation().x + evt.getX()-x, this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_moverMouseDragged

    private void moverMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moverMouseMoved
        minimizar.setBackground(new Color(46, 51, 58));
        Icon foto = new ImageIcon(getClass().getResource("/img/return.png"));
        minimizar1.setIcon(foto);
    }//GEN-LAST:event_moverMouseMoved

    private void moverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moverMouseClicked
        minimizar.setBackground(new Color(46, 51, 58));
        x=this.getX();
        y=this.getY();
    }//GEN-LAST:event_moverMouseClicked

    private void moverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moverMouseEntered
        mover.setBackground(new Color(0, 102, 102));
    }//GEN-LAST:event_moverMouseEntered

    private void moverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moverMouseExited
        mover.setBackground(new Color(0, 102, 102));
    }//GEN-LAST:event_moverMouseExited

    private void moverMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moverMousePressed
        x= evt.getX();
        y= evt.getY();
    }//GEN-LAST:event_moverMousePressed

    private void cerrarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarMouseMoved
        cerrar.setBackground(Color.red);
        minimizar.setBackground(new Color(46, 51, 58));
    }//GEN-LAST:event_cerrarMouseMoved

    private void cerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarMouseClicked
        //this.dispose(); no utilizo el dispose para que termine losnhilos activos
        System.exit(0);
    }//GEN-LAST:event_cerrarMouseClicked

    private void minimizarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizarMouseMoved
        minimizar.setBackground(new Color(32, 178, 170));
        cerrar.setBackground(new Color(46, 51, 58));
        Icon foto = new ImageIcon(getClass().getResource("/img/return.png"));
        minimizar1.setIcon(foto);
    }//GEN-LAST:event_minimizarMouseMoved

    private void minimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizarMouseClicked
        this.setExtendedState(ICONIFIED);
        minimizar.setBackground(new Color(0, 102, 102));
    }//GEN-LAST:event_minimizarMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

    }//GEN-LAST:event_jButton2ActionPerformed

    private void minimizar1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizar1MouseMoved
        minimizar.setBackground(new Color(46, 51, 58));
        Icon foto = new ImageIcon(getClass().getResource("/img/return2.png"));
        minimizar1.setIcon(foto);
    }//GEN-LAST:event_minimizar1MouseMoved

    private void minimizar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizar1MouseClicked
        MenuPrincipal ventana = new MenuPrincipal(id_vend);
        this.dispose();
        ventana.setVisible(true);
    }//GEN-LAST:event_minimizar1MouseClicked

    private void txtNombreDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreDActionPerformed

    private void txtDescripcionCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescripcionCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescripcionCActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        if (connect.RegistrarDir(txtNombreD.getText())) {
            JOptionPane.showMessageDialog(null,"Director Registrado");
            
            cbDirector.removeAllItems();
            ArrayList<source.Director> directores = new ArrayList<>();
            directores = connect.llenarDirectores();
            for(source.Director director : directores){
                cbDirector.addItem( director.getId() + " " + director.getNombre());
            }
            
        }
        else{
            JOptionPane.showMessageDialog(null, "Director NO registrado");
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        if (connect.RegistrarCat(txtDescripcionC.getText())) {
            JOptionPane.showMessageDialog(null,"Categoria Registrada");
            ArrayList<source.Categoria> categorias = new ArrayList<>();
            categorias = connect.llenarCategorias();
            cbCategoria.removeAllItems();
            for(source.Categoria categoria : categorias){
                cbCategoria.addItem( categoria.getId() + " " + categoria.getDescripcion());
            }
        } else{
            JOptionPane.showMessageDialog(null, "Categoria NO registrada");
        }
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        if (connect.registrarPelicula(cbDirector.getSelectedIndex() + 1, txtTitulo.getText(), Integer.parseInt(txtDia.getText()),
                Integer.parseInt(txtMes.getText()), Integer.parseInt(txtAnno.getText()))) {
            JOptionPane.showMessageDialog(null,"Pelicula Registrada Correctamente.");
        } else{
            JOptionPane.showMessageDialog(null,"Pelicula NO Registrada Correctamente.");
        }
    }//GEN-LAST:event_jButton2MouseClicked

    private void btnAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarMouseClicked
        if (codigoo != -1) {
            if (connect.Agregar_Peli_Cate(nombre_peli, (String) cbCategoria.getSelectedItem())) {
                JOptionPane.showMessageDialog(null, "Categoria '" + cbCategoria.getSelectedItem() +
                        "'\n Agregada a la pelicula '" + nombre_peli + "' exitosamente!");
                btnAgregar.enable(false);
            }
            codigoo = -1;
        } else{
            JOptionPane.showMessageDialog(null, "Recuerda seleccionar una pelicula y su respectiva categoria por agregar.");
        }
    }//GEN-LAST:event_btnAgregarMouseClicked

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void txtTituloBKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTituloBKeyReleased
        ArrayList<source.Pelicula> iPeliculas = new ArrayList<>();
        iPeliculas = connect.buscaPelicula(txtTituloB.getText().toUpperCase());
        dtm.setRowCount(0);
        
        for (source.Pelicula iPeli : iPeliculas) {
            dtm.addRow(new Object[]{
                iPeli.getId(),
                iPeli.getNombre_pelicula(),
            });
        }
        
    }//GEN-LAST:event_txtTituloBKeyReleased

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int algo = jTable1.getSelectedRow();
        String bus = "" + dtm.getValueAt(algo, 0);
        nombre_peli = (String) dtm.getValueAt(algo, 1);
        codigoo = Integer.parseInt(bus);
    }//GEN-LAST:event_jTable1MouseClicked

    private void cbCategoriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbCategoriaMouseClicked
        btnAgregar.enable(true);
    }//GEN-LAST:event_cbCategoriaMouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        if (codigon != -3) {
            if (connect.actualizar_format("" + dtm2.getValueAt(codigon, 0), Integer.parseInt(txt_f_precion.getText()))) {
                ArrayList<source.Formato> iformatos = new ArrayList<>();
            iformatos = connect.formatos();
            dtm2.setRowCount(0);
        
                for (source.Formato iForma : iformatos) {
                    dtm2.addRow(new Object[]{
                        iForma.getNombre_formato(),
                        iForma.getPrecio(),
                    });
                }
                JOptionPane.showMessageDialog(null, "Actualizado correctamente");
            } else{
                JOptionPane.showMessageDialog(null, "No actualizado correctamente");
            }
            codigon = -1;
        } else{
            JOptionPane.showMessageDialog(null, "Recuerda seleccionar un formato \n    para actualizarlo");
        }
    }//GEN-LAST:event_jButton4MouseClicked

    private void txt_f_precioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_f_precioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_f_precioActionPerformed

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        if (connect.agregar_formato(txt_f_nombre.getText(), Integer.parseInt(txt_f_precio.getText()))) {
            ArrayList<source.Formato> iformatos = new ArrayList<>();
            iformatos = connect.formatos();
            dtm2.setRowCount(0);
        
            for (source.Formato iForma : iformatos) {
                dtm2.addRow(new Object[]{
                    iForma.getNombre_formato(),
                    iForma.getPrecio(),
                });
            }
            JOptionPane.showMessageDialog(null, "Formato Registrado");
        } else{
            JOptionPane.showMessageDialog(null, "Formato NO Registrado");
        }
    }//GEN-LAST:event_jButton5MouseClicked

    private void txt_f_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_f_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_f_nombreActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
    codigon = jTable2.getSelectedRow();
    txt_f_precion.setText( "" + dtm2.getValueAt(codigon, 1));
    }//GEN-LAST:event_jTable2MouseClicked

    private void txt_f_precionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_f_precionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_f_precionActionPerformed

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        if (codigo_peli_ejemplar != -1) {
            if (codigo_formato_ejemplar != -1) {
                if (Integer.parseInt(txt_cantidad.getText()) > 0) {
                    if (connect.ingreso_de_ejemplares(""+jTable3.getValueAt(codigo_peli_ejemplar, 1),
                            ""+jTable4.getValueAt(codigo_formato_ejemplar, 0), Integer.parseInt(txt_cantidad.getText()))) {
                        codigo_peli_ejemplar = -1;
                        codigo_formato_ejemplar = -1;
                        txt_cantidad.setText("0");
                        JOptionPane.showMessageDialog(null, "Registro realizado!");
                    } else{
                        JOptionPane.showMessageDialog(null, "Registro No realizado correctamente!");
                    }
                } else{
                    JOptionPane.showMessageDialog(null, "Recuerda ingresar una cantidad correcta de peliculas.");
                }
            } else{
                JOptionPane.showMessageDialog(null, "Recuerda Seleccionar el formato para los ejemplares.");
            }
        } else{
            JOptionPane.showMessageDialog(null, "Recuerda Seleccionar la pelicula a la que se le ingresaran ejemplares.");
        }
    }//GEN-LAST:event_jButton6MouseClicked

    private void txtTituloB1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTituloB1KeyReleased
        ArrayList<source.Pelicula> iPeliculas = new ArrayList<>();
        iPeliculas = connect.buscaPelicula(txtTituloB1.getText().toUpperCase());
        dtm3.setRowCount(0);
        
        for (source.Pelicula iPeli : iPeliculas) {
            dtm3.addRow(new Object[]{
                iPeli.getId(),
                iPeli.getNombre_pelicula(),
            });
        }
    }//GEN-LAST:event_txtTituloB1KeyReleased

    private void jTable3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable3MouseClicked
        codigo_peli_ejemplar = jTable3.getSelectedRow();
    }//GEN-LAST:event_jTable3MouseClicked

    private void jTable4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable4MouseClicked
        codigo_formato_ejemplar = jTable4.getSelectedRow();
    }//GEN-LAST:event_jTable4MouseClicked

    private void txt_cantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cantidadActionPerformed

    private void jButton6MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseMoved
        jButton6.setBackground(new Color(70, 130, 130));
    }//GEN-LAST:event_jButton6MouseMoved

    private void jPanel8MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel8MouseMoved
        jButton6.setBackground(new Color(100, 150, 150));
    }//GEN-LAST:event_jPanel8MouseMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pelicula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pelicula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pelicula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pelicula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pelicula(id_vend).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ColorBarra;
    private javax.swing.JPanel Director_Categoria;
    private javax.swing.JPanel Ejemplares;
    private javax.swing.JPanel Formato;
    private javax.swing.JPanel Registrar;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JComboBox<String> cbCategoria;
    private javax.swing.JComboBox<String> cbDirector;
    private javax.swing.JButton cerrar;
    private javax.swing.JLabel fondo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JButton minimizar;
    private javax.swing.JButton minimizar1;
    private javax.swing.JButton mover;
    private javax.swing.JTextField txtAnno;
    private javax.swing.JTextField txtDescripcionC;
    private javax.swing.JTextField txtDia;
    private javax.swing.JTextField txtMes;
    private javax.swing.JTextField txtNombreD;
    private javax.swing.JTextField txtTitulo;
    private javax.swing.JTextField txtTituloB;
    private javax.swing.JTextField txtTituloB1;
    private javax.swing.JTextField txt_cantidad;
    private javax.swing.JTextField txt_f_nombre;
    private javax.swing.JTextField txt_f_precio;
    private javax.swing.JTextField txt_f_precion;
    // End of variables declaration//GEN-END:variables
}
